SavedToDoList/SavedToDoList/Models/ErrorViewModel.cs
using System;

namespace SavedToDoList.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

SavedToDoList/SavedToDoList/Models/ToDoListModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SavedToDoList.Models
{
    public class ToDoListModel
    {
        public string Name { get; set; }
        public string Description { get; set; }
    }
}

SavedToDoList/SavedToDoList/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using SavedToDoList.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace SavedToDoList.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

SavedToDoList/SavedToDoList/Controllers/ToDoListController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using SavedToDoList.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SavedToDoList.Controllers
{
    public class ToDoListController : Controller
    {
        public IActionResult Index()
        {
           
            return View();
        }

        public IActionResult SubmitEntry(ToDoListModel model)
        {
            string readModels = System.IO.File.ReadAllText("List.json");
            List<ToDoListModel> receivedModels = JsonConvert.DeserializeObject<List<ToDoListModel>>(readModels);

            if (receivedModels == null)
            {
                receivedModels = new();
            }

            receivedModels.Add(model);


            string jsonModels = JsonConvert.SerializeObject(receivedModels);

            System.IO.File.WriteAllText("List.json", jsonModels);

            return View("EditSuccessful");

        }

        public IActionResult ToDoListDisplay()
        {
            string readModels = System.IO.File.ReadAllText("List.json");
            List<ToDoListModel> receivedModels = JsonConvert.DeserializeObject<List<ToDoListModel>>(readModels);

            if (receivedModels == null)
            {
                receivedModels = new();
            }
            return View(receivedModels);
        }

    }   
}

SavedToDoList/SavedToDoList/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

SavedToDoList/SavedToDoList/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SavedToDoList</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">SavedToDoList</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ToDoList" asp-action="Index">Entry</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ToDoList" asp-action="ToDoListDisplay">To Do List</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - SavedToDoList - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

SavedToDoList/SavedToDoList/Views/ToDoList/EditSuccessful.cshtml
<h2>Your To Do List successfully updated!</h2>

SavedToDoList/SavedToDoList/Views/ToDoList/Index.cshtml
@model ToDoListModel

<h4>Enter The Task</h4>


    @using (Html.BeginForm("SubmitEntry", "ToDoList", FormMethod.Post))
    {
        <div class="container-full" style="background-color: white; padding: 20px">
            <div class="container">
                @Html.LabelFor(x => x.Name)
                @Html.TextBoxFor(x => x.Name)
                @Html.LabelFor(x => x.Description)
                @Html.TextBoxFor(x => x.Description)
                <input class="btn btn-primary" type="submit" value="Submit" />
            </div>
        </div>
    }

SavedToDoList/SavedToDoList/Views/ToDoList/ToDoListDisplay.cshtml
@model List<ToDoListModel>

<h2>My To Do List:</h2>

<table class="table">
    <tr>
        <th>Name</th>
        <th>Description</th>
        <th>Actions</th>
    </tr>
    @foreach (ToDoListModel toDoListModel in @Model)
    {
<tr>
    <td>@toDoListModel.Name</td>
    <td>@toDoListModel.Description</td>
    <td><input class="btn btn-danger" type="submit" value="Delete" /> <input class="btn btn-primary" type="submit" value="Done" /></td>
</tr>
    }
</table>