WebApplicationGames/WebApplicationGames/Models/ErrorViewModel.cs
using System;

namespace WebApplicationGames.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

WebApplicationGames/WebApplicationGames/Models/GuessANumberModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace WebApplicationGames.Models
{
    public class GuessANumberModel
    {
        [Required(ErrorMessage = "Please Enter Your Guess!")]
        public int? Player { get; set; }
        public int Computer { get; set; }
        public string Winner { get; set; }
    }
}

WebApplicationGames/WebApplicationGames/Models/GuessAWordModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebApplicationGames.Models
{
    public class GuessAWordModel
    {
        public string Player { get; set; }
        public string Computer { get; set; }
        public string Hint { get; set; }
        public string Winner { get; set; }

    }
}

WebApplicationGames/WebApplicationGames/Models/RockPaperScissorsModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace WebApplicationGames.Models
{
    public class RockPaperScissorsModel
    {
        [Required(ErrorMessage = "Please Enter Your Choice!")]
        public string Player { get; set; }
        public string Computer { get; set; }
        public string Winner { get; set; }

    }
}

WebApplicationGames/WebApplicationGames/Controllers/GameController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WebApplicationGames.Models;

namespace WebApplicationGames.Controllers
{
    public class GameController : Controller
    {
        public IActionResult Index()
        {
            return View("index");
        }
        public IActionResult RockPaperScissors()
        {
            RockPaperScissorsModel model = new RockPaperScissorsModel();
            return View(model);
        }

        public IActionResult RockPaperScissorsPlay(RockPaperScissorsModel model)
        {
            if (!ModelState.IsValid)
            {
                return View("RockPaperScissors", model);
            }

            Random rnd = new Random();
            string[] options = { "Rock", "Paper", "Scissors" };
            model.Computer = options[rnd.Next(0, 3)];
            model.Player = System.Globalization.CultureInfo.CurrentCulture.TextInfo.ToTitleCase(model.Player.ToLower());

                switch (model.Computer)
                {
                    case "Rock":
                        if (model.Player == "Rock")
                        {
                            model.Winner = "Tie";
                        }
                        if (model.Player == "Paper")
                        {
                            model.Winner = "Player";
                        }
                        if (model.Player == "Scissors")
                        {
                            model.Winner = "Computer";
                        }
                        break;

                    case "Paper":
                        if (model.Player == "Paper")
                        {
                            model.Winner = "Tie";
                        }
                        if (model.Player == "Rock")
                        {
                            model.Winner = "Computer";
                        }
                        if (model.Player == "Scissors")
                        {
                            model.Winner = "Player";
                        }
                        break;

                    case "Scissors":
                        if (model.Player == "Scissors")
                        {
                            model.Winner = "Tie";
                        }
                        if (model.Player == "Rock")
                        {
                            model.Winner = "Player";
                        }
                        if (model.Player == "Paper")
                        {
                            model.Winner = "Computer";
                        }
                        break;
                }
                return View("RockPaperScissors", model);

            
        }

        public IActionResult GuessANumber()
        {
            GuessANumberModel model = new GuessANumberModel();
            return View(model);
        }

        public IActionResult GuessANumberPlay(GuessANumberModel model)
        {
            Random rnd = new Random();
            int[] options = { 1,2,3,4,5,6,7,8,9,10 };
            model.Computer = options[rnd.Next(0, 10)];

            if (model.Player == model.Computer)
            {
                model.Winner = "Player";
            }
            if (model.Player > model.Computer || model.Player < model.Computer)
            {
                model.Winner = "Computer";
            }

            return View("GuessANumber", model);
        }

        public IActionResult GuessAWord()
        {
            GuessAWordModel model = new GuessAWordModel();
            return View(model);
        }

        public IActionResult GuessAWordPlay(GuessAWordModel model)
        {
            Random rnd = new Random();
            string[] options = { "Watermellon", "Calendar", "Database", "Festival", "Triangle" };
            model.Computer = options[rnd.Next(0, 5)];
            model.Player = System.Globalization.CultureInfo.CurrentCulture.TextInfo.ToTitleCase(model.Player.ToLower());
            model.Hint = 


            return View("GuessAWord", model);
        }
    }



}

WebApplicationGames/WebApplicationGames/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using WebApplicationGames.Models;

namespace WebApplicationGames.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

WebApplicationGames/WebApplicationGames/Views/Game/GuessANumber.cshtml
@model GuessANumberModel

@if (Model.Player != null)
{
    <h3>Your Guess: @Model.Player</h3>
    <h3>Correct Answer: @Model.Computer</h3>

    if (Model.Winner == "Player")
    {
        <h2 style="color:darkblue">Congrats Your Guess is Correct!</h2>
    }

    if (Model.Winner == "Computer")
    {
        <h2 style="color:darkblue">Your Guess is incorrect...</h2>
    }

}

@using (Html.BeginForm("GuessANumberPlay", "Game", FormMethod.Post))
{
    <div class="container-full" style="background-color:white">
        <div class="container">
            <p>Please enter guess from 1 to 10</p>
            @Html.LabelFor(x => x.Player)
            @Html.TextBoxFor(x => x.Player)
            <p style="color:red">@Html.ValidationMessageFor(x => x.Player)</p>
            <input class="btn btn-primary" type="submit" value="Guess!" />
        </div>
    </div>
}

WebApplicationGames/WebApplicationGames/Views/Game/GuessAWord.cshtml
@model GuessAWordModel

@if (Model.Player != null)
{
    <h3>Your Guess: @Model.Player</h3>
    <h3>Correct Answer: @Model.Computer</h3>

    if (Model.Winner == "Player")
    {
        <h2 style="color:darkblue">Congrats Your Guess is Correct!</h2>
    }

    if (Model.Winner == "Computer")
    {
        <h2 style="color:darkblue">Your Guess is incorrect...</h2>
    }

}

@using (Html.BeginForm("GuessANumberPlay", "Game", FormMethod.Post))
{
    <div class="container-full" style="background-color:white">
        <div class="container">
            <p>Please enter guess from 1 to 10</p>
            @Html.LabelFor(x => x.Player)
            @Html.TextBoxFor(x => x.Player)
            <p style="color:red">@Html.ValidationMessageFor(x => x.Player)</p>
            <input class="btn btn-primary" type="submit" value="Guess!" />
        </div>
    </div>
}

WebApplicationGames/WebApplicationGames/Views/Game/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<h2>What game do you wanna play?</h2>

@using (Html.BeginForm("RockPaperScissors", "Game", FormMethod.Get))
{
    <div class="container-full" style="background-color:white">
        <div class="container">
            <input class="btn btn-primary" style="margin-top:10px" type="submit" value="Rock Paper Scissors" />
        </div>
    </div>
}


@using (Html.BeginForm("GuessANumber", "Game", FormMethod.Get))
{
    <div class="container-full" style="background-color:white">
        <div class="container">
            <input class="btn btn-primary" style="margin-top:10px" type="submit" value="Guess A Number" />
        </div>
    </div>
}

@using (Html.BeginForm("GuessAWord", "Game", FormMethod.Get))
{
    <div class="container-full" style="background-color:white">
        <div class="container">
            <input class="btn btn-primary" style="margin-top:10px" type="submit" value="Guess A Word" />
        </div>
    </div>
}

WebApplicationGames/WebApplicationGames/Views/Game/RockPaperScissors.cshtml
@model RockPaperScissorsModel

@if (Model.Player != null)
{
    <h3>You Chose: @Model.Player</h3>
    <h3>Computer Chose: @Model.Computer</h3>

    if (Model.Winner == "Tie")
    {
        <h2 style="color:darkblue">Game Result is @Model.Winner</h2>
    }

    if (Model.Winner == "Player")
    {
        <h2 style="color:darkblue">Congrats You Win!</h2>
    }

    if (Model.Winner == "Computer")
    {
        <h2 style="color:darkblue">You loose...</h2>
    }


}

@using (Html.BeginForm("RockPaperScissorsPlay", "Game", FormMethod.Post))
{
    <div class="container-full" style="background-color:white">
        <div class="container">
            @Html.LabelFor(x => x.Player)
            @Html.TextBoxFor(x => x.Player)
            <p style="color:red">@Html.ValidationMessageFor(x => x.Player)</p>
            <input class="btn btn-primary" type="submit" value="Play!" />
        </div>
    </div>
}

WebApplicationGames/WebApplicationGames/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebApplicationGames</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WebApplicationGames</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Game" asp-action="Index">Games</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - WebApplicationGames - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>